---

- name: rabbitmq | configure ulimit
  template:
    src: "rabbitmq-server.j2"
    dest: "/etc/default/rabbitmq-server"
    owner: root
    group: root
    mode: 0644
  become: yes
  become_method: sudo
  notify: restart rabbitmq

- name: rabbitmq | configure erlang cookie | check
  copy:
    dest: "/var/lib/rabbitmq/.erlang.cookie.copy"
    content: "{{ rabbitmq_erlang_cookie }}"
    owner: rabbitmq
    group: rabbitmq
    mode: 0400
    backup: yes
  become: yes
  become_method: sudo
  register: cookie

- name: rabbitmq | stop service
  service:
    name: rabbitmq-server
    state: stopped
  become: yes
  become_method: sudo
  when: cookie is defined and cookie|changed

- name: rabbitmq | configure erlang cookie
  copy:
    dest: "/var/lib/rabbitmq/.erlang.cookie"
    content: "{{ rabbitmq_erlang_cookie }}"
    owner: rabbitmq
    group: rabbitmq
    mode: 0400
    backup: yes
  become: yes
  become_method: sudo
  notify: restart rabbitmq

- meta: flush_handlers

- name: rabbitmq | config file
  template:
    src: "rabbitmq.config.j2"
    dest: "/etc/rabbitmq/rabbitmq.config"
    owner: root
    group: root
    mode: 0644
  become: yes
  become_method: sudo
  notify: restart rabbitmq

- name: rabbitmq | env file
  template:
    src: "rabbitmq-env.conf.j2"
    dest: "/etc/rabbitmq/rabbitmq-env.conf"
    owner: root
    group: root
    mode: 0644
  become: yes
  become_method: sudo
  notify: restart rabbitmq

- name: rabbitmq | download plugins
  get_url:
    url: "{{ item }}"
    dest: "/usr/lib/rabbitmq/lib/rabbitmq_server-{{ rabbitmq_version.split('-') | first }}/plugins//{{ item | basename }}"
    owner: rabbitmq
    group: rabbitmq
    mode: 0644
  with_items: rabbitmq_download_plugins
  become: yes
  become_method: sudo

- name: rabbitmq | enable plugins
  rabbitmq_plugin:
    names: "{{ item }}"
    state: enabled
  with_items: rabbitmq_plugins
  become: yes
  become_method: sudo
  notify: restart rabbitmq
